# Generated by Django 4.2.23 on 2025-07-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=140, verbose_name='Название')),
                ('cardtext', models.TextField(verbose_name='Заметка')),
                ('formatted', models.TextField(blank=True, editable=False)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('comments', models.IntegerField(default=0, editable=False, verbose_name='Комментариев')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Рейтинг заметки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Заметку',
                'verbose_name_plural': 'Заметка',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('has_cards', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Есть статьи')),
                ('sort', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField()),
                ('has_cards', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='Есть статьи')),
                ('sort', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.category')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='CardsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images', verbose_name='Изображение')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавленo')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cards', verbose_name='Заметка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заливший')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.tag', verbose_name='Тег'),
        ),
        migrations.CreateModel(
            name='CardFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена в избранное')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cards', verbose_name='Заметка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
        ),
    ]
